buildspec_content = <<EOF
version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:        
    commands:
      - echo Building...
      - mkdir -p output
      - echo "hello from build" > output/hello.txt

artifacts:
  files:
    - output/**/*

post_build:
  commands:
    - echo "Build complete. Final files:"
    - ls -R
EOF
